# hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: single-tier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: single-tier # It targets the Deployment named 'single-tier'.

  minReplicas: 1 # Minimum number of pods
  maxReplicas: 10 # Maximum number of pods

  # Define the metrics that will trigger scaling actions.
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
